name: Dotnet Run

on:
  workflow_dispatch:
  push:
    branches: [main, SprintTwo, NewWorkflow]
  pull_request:
    branches: [main, SprintTwo]

jobs:
  mac-build-check:
    runs-on: mac-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

